{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cypher-agent.fullname" . }}-auth
  labels:
    {{- include "cypher-agent.labels" . | nindent 4 }}
type: Opaque
data:
  AGENT_KEY_ID: {{ .Values.auth.agentKeyId | b64enc | quote }}
  AGENT_KEY_SECRET: {{ .Values.auth.agentKeySecret | b64enc | quote }}
{{- end }}
